### ISSUE TITLE
Wiki link missing

### ISSUE THREAD

**Issue by micuat** [sccn/xdf#11]
the link to `xdfimport` on https://sccn.ucsd.edu/wiki/EEGLAB_Extensions goes to 403 error:
http://sccn.ucsd.edu/eeglab/plugins/xdfimport1.13.zip

**Comment by clementlee2000** [comment]
T he SCCN servers were being upgraded this past weekend. Do you still have this issue?

**Comment by sappelhoff** [comment]
it's working now.

**Comment by arnodelorme** [comment]
Closing this issue
