### ISSUE TITLE
The error I get: not a valid XDF file!

### ISSUE THREAD

**Issue by fatemeh66** [sccn/xdf#16]
I am sure the XDF file is valid, but I get this error.

**Comment by fatemeh66** [comment]
@cboulay

**Comment by cboulay** [comment]
How did you try to open it? Python, Matlab, using libxdf (which hasn't been merged yet, sorry!).

**Comment by fatemeh66** [comment]
In Jupyter (python).

**Comment by cboulay** [comment]
Can you please post some sample code and if possible post a minimal file that generates this error?

Also, have you tried opening the xdf file with [XDFBrowser](https://github.com/labstreaminglayer/App-XDFBrowser) or Matlab?

**Comment by fatemeh66** [comment]
I opened the file in RStudio. 

Here is the code:
dataframe_blobdata = load_xdf(LOCALFILENAME)
The result:
Importing XDF file Line1.xdf...

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-103-9a06639ea186> in <module>()
----> 1 dataframe_blobdata = load_xdf(LOCALFILENAME)

<ipython-input-87-87b5d68c9925> in load_xdf(filename, on_chunk, verbose, synchronize_clocks, handle_clock_resets, dejitter_timestamps, jitter_break_threshold_seconds, jitter_break_threshold_samples, clock_reset_threshold_seconds, clock_reset_threshold_stds, clock_reset_threshold_offset_seconds, clock_reset_threshold_offset_stds, winsor_threshold)
     75         # read [MagicCode]
     76          if f.read(4) != b'XDF:':
---> 77             raise Exception('not a valid XDF file: %s' % filename)
     78 
     79        # for each chunk...

Exception: not a valid XDF file: Line1.xdf

**Comment by cboulay** [comment]
I didn't realize there was an xdf importer for R. Can you tell me more about that?

But, on topic, how was this xdf file created?

**Comment by fatemeh66** [comment]
We can use xdf files in Microsoft R. The details of creating and using this sort of file is explained in the following link:
https://docs.microsoft.com/en-us/machine-learning-server/r/concept-what-is-xdf

**Comment by cboulay** [comment]
They have the same file extension but they have nothing to do with each other. Microsoft's xdf file format is not the same as sccn/labstreaminglayer's xdf file format.

**Comment by fatemeh66** [comment]
Yes, you are right
