### ISSUE TITLE
mex files for mac?

### ISSUE THREAD

**Issue by cll008** [sccn/xdf#27]
It seems the mex file distributed in the EEGLAB plugin 'xdfimport1.13' is throwing errors on newer macs. Any ideas / source for newer, compatible mex files?

**Comment by arnodelorme** [comment]
Yes, we should recompile or remove the executable files (because there is a native Matlab import). @chkothe suggested having a smart mecanism to choose which importer to use.

**Comment by cboulay** [comment]
For new people that might stop by while searching for the same problem:

If you delete the .mexmaci64 files that come with the importer then the importer should work again, although slowly.
