### ISSUE TITLE
's' not defined when processing xdf on_chunk

### ISSUE THREAD

**Issue by bdyetton** [sccn/xdf#32]
Hi there,
Thanks for pyxdf :)
There is a small bug, line 308 of pyxdf:
```
values, stamps, streams[StreamId] = on_chunk(values, stamps,
                                                              streams[StreamId], s)
```
should be:
``` 
values, stamps, streams[StreamId] = on_chunk(values, stamps,
                                                              streams[StreamId], StreamId)
```

Also note that the super vague try/except block there will catch errors from the users on_chunk function.
This seams like a bad call, and makes the user think there xdf if corrupt, when really there on_chunk function has some simple error.

**Comment by cbrnr** [comment]
Fixed in https://github.com/xdf-modules/xdf-Python/pull/5.
