### ISSUE TITLE
minimal.xdf vs. specification incongruence

### ISSUE THREAD

**Issue by Garfield100** [sccn/xdf#61]
It seems to me as if the [spec](../wiki/Specifications) and the [minimal.xdf](https://github.com/xdf-modules/example-files/blob/7a66644c6fdbf76a3bff727f8c7c81f2a60213ce/minimal.xdf) example file in the linked example_files repo disagree.
While writing a new xdf parser, I tried reading values according to this: [Structure of Value](https://github.com/sccn/xdf/wiki/Specifications#structure-of-value)  
I made sure to assert as much as possible in general, including the following from the linked paragraphs:

_For non-numeric (i.e., string or binary) values, a variable-length encoding is used:_

<pre>
[NumLengthBytes] [Length] [StringContent] 
[4, or 8] [...] [Arbitrary] 
[1] [As encoded] [Length] 
</pre>

Here, the number of length bytes is specified to be either 4, or 8. However, my program throws an error because this is not the case in minimal.xdf:
![image](https://user-images.githubusercontent.com/5878721/227719169-c3d3eb5e-b648-497f-b4cc-463b63e45c22.png)

As you can see, the length of the string `Hello` is given by only a single byte, `05`.

I checked the commits on the wiki and the specified `[4, or 8]` was already in the initial commit.
Strangely though, there _was_ also a `1` but it wasn't inside the square brackets:
![image](https://user-images.githubusercontent.com/5878721/227719736-a1397d75-ab1a-40cd-a281-0064c7ac4e85.png)

As such, it was removed in the following clean-up commit. I'm not sure how the wiki came to be or why the first commit looked the way it did. Perhaps the 1 was supposed to stay and be included in the square brackets?

Is the file or the spec outdated or otherwise wrong?
Have I missed something else entirely?

**Comment by chkothe** [comment]
Hi Enrico, good catch, and hopefully it didn't cause too much frustration! I think this error must have crept in when the spec was originally converted to GitHub wiki format. Indeed, this originally said `[1, 4, or 8]` just like the other variable-length encoded integers (that's why there's still a comma after the 4).

Edit: fixed now
